stages:
  - build

unity-build:
  image: gableroux/unity3d:2022.3.5f1  # Replace with your Unity version
  stage: build
  script:
    - /opt/Unity/Editor/Unity -batchmode -nographics \
      -projectPath . \
      -buildTarget Win64 \
      -output ./Builds/Windows/MyGame.exe
  artifacts:
    paths:
      - Builds/  # Store the built files